import React from 'react';

export const createFileChangeEvent = (files: FileList): React.ChangeEvent<HTMLInputElement> => {
  return {
    bubbles: false,
    cancelable: false,
    currentTarget: null,
    defaultPrevented: false,
    eventPhase: 0,
    isTrusted: false,
    nativeEvent: null,
    preventDefault: () => {},
    stopPropagation: () => {},
    stopImmediatePropagation: () => {},
    target: {
      files,
      value: '',
      name: '',
      type: 'file',
      checked: false,
      defaultChecked: false,
      defaultValue: '',
      disabled: false,
      form: null,
      readOnly: false,
      required: false,
      tabIndex: -1,
      accept: '',
      capture: '',
      multiple: false,
      onchange: () => {},
      onclick: () => {},
      oninput: () => {},
      onfocus: () => {},
      onblur: () => {},
      oninvalid: () => {},
      onreset: () => {},
      onsubmit: () => {},
      ondragstart: () => {},
      ondragend: () => {},
      ondragenter: () => {},
      ondragleave: () => {},
      ondragover: () => {},
      ondrag: () => {},
      ondrop: () => {},
      onkeydown: () => {},
      onkeypress: () => {},
      onkeyup: () => {},
      onmousedown: () => {},
      onmouseenter: () => {},
      onmouseleave: () => {},
      onmousemove: () => {},
      onmouseout: () => {},
      onmouseover: () => {},
      onmouseup: () => {},
      ontouchcancel: () => {},
      ontouchend: () => {},
      ontouchmove: () => {},
      ontouchstart: () => {},
      onscroll: () => {},
      onwheel: () => {},
      oncopy: () => {},
      oncut: () => {},
      onpaste: () => {},
      oncompositionend: () => {},
      oncompositionstart: () => {},
      oncompositionupdate: () => {},
      onbeforeinput: () => {},
      onsearch: () => {},
      oncontextmenu: () => {},
      ondblclick: () => {},
      ondragexit: () => {},
      onpointercancel: () => {},
      onpointerdown: () => {},
      onpointerenter: () => {},
      onpointerleave: () => {},
      onpointermove: () => {},
      onpointerout: () => {},
      onpointerover: () => {},
      onpointerup: () => {},
      ongotpointercapture: () => {},
      onlostpointercapture: () => {},
      onbeforeprint: () => {},
      onafterprint: () => {},
      onbeforeunload: () => {},
      onhashchange: () => {},
      onlanguagechange: () => {},
      onmessage: () => {},
      onoffline: () => {},
      ononline: () => {},
      onpopstate: () => {},
      onstorage: () => {},
      onunload: () => {}
    },
    timeStamp: 0,
    type: 'change'
  } as React.ChangeEvent<HTMLInputElement>;
};
